language: node_js
sudo: false
node_js:
  - "10"
  - "12"
  - "node"

before_script:
  - "npm -g install npm@latest"

script:
  - "npm run cover"

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
